collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9032258
color:
  saturation: 0.9283154
  brandStrength: 0.8422939
  lightness: 0.2473118
  brandColors:
    - '#FFFFFF'
    - '#A50000'
    - '#000000'
    - '#BF4C4C'
    - '#F2DADA'
  rhythmicContrast: 0.516129
layout_spectrum: 0.202509
name: Tiena
