name: Tiena
favicon: null
layout_spectrum: 0.202509
typography_spectrum: 0.31457
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A60000'
    - '#FFFFFF'
    - '#000001'
    - '#D64247'
    - '#D8BDBD'
  brandStrength: 0.75
  lightness: 0.5745614
  saturation: 0.4943609
  rhythmicContrast: 0.3565163
purpose: []
