layout_spectrum: 0.202509
favicon: null
name: Tiena
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.8422939
  lightness: 0.2473118
  saturation: 0.9283154
  rhythmicContrast: 0.516129
  brandColors:
    - '#A60000'
    - '#FFFFFF'
    - '#000001'
    - '#D64247'
    - '#D8BDBD'
typography_spectrum: 0.6711636
